### ISSUE TITLE
Add start-date tracking on the milestone description

### ISSUE THREAD

**Issue by Eguzkiman** [Eguzkiman/git-gantt#1]
## Summary
Parse a starting date from the milestone description, and use it as a starting date for the gantt-chart.

## Motivation
We're currently using the milestones' `createdAt` field as the starting date for the chart's tasks. As this field is not customizable, and there is no other field that is useful for this purpose, it'd be great to have a custom field.

## Checklist
- [x] Retrieve the milestones' description
- [x] Parse the description to find a token in this format: `starts:DD-MM-YYYY`
- [x] Use the parsed date as starting date for each task. If the date is not present, default to `createdAt`
