### ISSUE TITLE
Update milestones dates on drag

### ISSUE THREAD

**Issue by Eguzkiman** [Eguzkiman/git-gantt#3]
## Summary

Whenever a task is dragged on the gantt chart, it should update the corresponding milestone's due date and start date.

## Motivation

Currently, the only way to modify a milestone's due date & start date is by clicking it, then editing the dates on GitHub. With drag, i'd be much faster!

## Checklist

- [ ] Re-enable dragging tasks on the gantt component
- [ ] Add the update-milestone GraphQL mutation
- [ ] Make the drag event trigger the update-milestone mutation
- [ ] Add loading & error states
