### ISSUE TITLE
Add new milestones

### ISSUE THREAD

**Issue by Eguzkiman** [Eguzkiman/git-gantt#4]
## Summary

Make it possible to create new milestones from GitGantt!

## Motivation

It's annoying to have to create milestones on github, edit the dates there, and then refreshing GitGantt to see the result. It'd be much easier if milestones were created from GitGantt itself.

## Checklist

- [ ] Add a create milestone button
- [ ] Make the button display a milestone form on click
- [ ] The milestone form should ask for:
1. The project the milestone belongs to
2. The milestone's name
3. Due date & start date

- [ ] Add the create milestone mutation
- [ ] Run the mutation on form submit
